apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: rng
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rng
  template: 
    metadata: 
      labels: 
        app: rng        
    spec: 
      containers: 
        -
          image: rpozaisban/dockercoins:latest-rng
          name: rng
          imagePullPolicy: Always
          ports: 
            -
              containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hasher
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: hasher
  template: 
    metadata: 
      labels: 
        app: hasher        
    spec: 
      containers: 
        -
          image: rpozaisban/dockercoins:latest-hasher
          name: hasher
          imagePullPolicy: Always
          ports: 
            -
              containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: redis
  template: 
    metadata: 
      labels: 
        app: redis        
    spec: 
      containers: 
        -
          image: redis:6.0.9-alpine3.12@sha256:aa31e6d2afc72d2222ed3953587197c324f615861771637a64053f9d99ba4b74
          name: redis
          imagePullPolicy: Always
          ports: 
            -
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            -
              mountPath: /data
              name: redis
      volumes:
        -
          name: redis
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webui
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webui
  template: 
    metadata: 
      labels: 
        app: webui        
    spec: 
      containers: 
        -
          image: rpozaisban/dockercoins:latest-webui
          name: webui
          imagePullPolicy: Always
          ports: 
            -
              containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker        
    spec: 
      containers: 
        -
          image: rpozaisban/dockercoins:latest-worker
          name: worker
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  ports:
    -
      port: 8080
      targetPort: 8080
  selector:
    app: hasher
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    -
      port: 6379
      targetPort: 6379
    -
      port: 8080
      targetPort: 8080
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  ports:
    -
      port: 8080
      targetPort: 8080
  selector:
    app: rng
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
    -
      port: 8080
      targetPort: 8080
  selector:
    app: webui
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
    -
      port: 8080
      targetPort: 8080
  selector:
    app: worker
---

